routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('dashboard');
});

Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');

Auth::routes();

// Dashboard
Route::get('/dashboard', 'HomeController@index')->name('dashboard');
// Store & Items Management
Route::resource('stores', 'StoreController');
Route::resource('items', 'ItemController');
Route::put('items/{id}/transfer', 'ItemController@transfer')->name('items.transfer');
Route::put('items/{id}/reduce', 'ItemController@reduce')->name('items.reduce');
// User Management
Route::resource('users', 'UserController');
// Unit Management
Route::resource('units', 'UnitController');
// Employee Management
Route::resource('employees', 'EmployeeController');
Route::put('employees/{id}/reset', 'EmployeeController@reset')->name('employees.reset');

Route::get('setting', 'SettingController@index')->name('setting');

app/Employee.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Employee extends Model
{
    use SoftDeletes;

    public function user()
    {
        return $this->belongsTo('App\User');
    }
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use App\User;
use App\Employee;
use Illuminate\Http\Request;

class EmployeeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $title = 'Daftar Pegawai';
        $href = '#';
        $icon = '';

        $employees = User::where('role_id', 2)->get();

        return view('employees.index', compact('title', 'href', 'icon', 'employees'));
    }

    public function create()
    {
        $title = 'Tambah Pegawai';
        $href = route('employees.index');
        $icon = 'fa fa-arrow-left';

        return view('employees.create', compact('title', 'href', 'icon'));
    }

    public function store(Request $request)
    {
        $name = $request->input('employee_name');
        $email = $request->input('email');
        $password = $request->input('password');

        $request->validate([
            'employee_name' => 'required',
            'email' => 'required|email',
            'password' => 'required|min:8'
        ],[
            'employee_name.required' => 'jangan dikosongi!',
            'email.required' => 'jangan dikosongi!',
            'email.email' => 'tidak sesuai format!',
            'password.required' => 'jangan dikosongi!',
            'password.min' => 'minimal 8 karakter!'
        ]);

        $user = new User();
        $user->name = $name;
        $user->email = $email;
        $user->role_id = 2;
        $user->password = bcrypt($password);
        $user->save();

        return redirect('employees')->with('message', 'Data pegawai berhasil ditambahkan');
    }

    public function edit($id)
    {
        $title = 'Edit Pegawai';
        $href = route('employees.index');
        $icon = 'fa fa-arrow-left';

        $employee = User::find($id);

        return view('employees.edit', compact('title', 'href', 'icon', 'employee'));
    }

    public function update(Request $request, $id)
    {
        $name = $request->input('employee_name');
        $email = $request->input('email');

        $employee = User::find($id);

        $request->validate([
            'employee_name' => 'required',
            'email' => 'unique:users,email,' . $employee->id,
        ],[
            'employee_name.required' => 'jangan dikosongi!',
            'email.required' => 'jangan dikosongi!',
            'email.email' => 'tidak sesuai format!',
            'email.unique' => 'sudah digunakan!',
            'password.required' => 'jangan dikosongi!',
            'password.min' => 'minimal 8 karakter!'
        ]);

        $user = User::find($id);
        $user->name = $name;
        $user->email = $email;
        $user->save();

        return redirect('employees')->with('message', 'Data pegawai berhasil diupdate!');
    }

    public function reset(Request $request, $id)
    {
        $password = $request->input('password');

        $request->validate([
            'password' => 'required|min:8'
        ],[
            'password.required' => 'jangan dikosongin!',
            'password.min' => 'minimal 8 karakter'
        ]);

        $user = User::find($id);
        $user->password = bcrypt($password);
        $user->save();

        return redirect('employees')->with('message', 'Password pegawai '.$user->name.' berhasil di update.');
    }

    public function destroy($id)
    {
        $user = User::find($id);
        $user->delete();

        return redirect('employees')->with('message', 'Data pegawai berhasil dihapus!');
    }
}

resources/views/employees/create.blade.php
@extends('layouts.template')

@section('content')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <ol class="breadcrumb">
            <li><a href="{{ url('dashboard') }}"><i class="fa fa-user"></i> Home</a></li>
            <li>Akun</li>
            <li>User</li>
            <li class="active">Tambah Baru</li>
        </ol>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <form action="{{ route('employees.store') }}" method="POST">
                    @csrf

                    <div class="form-group">
                        <label for="">
                            Nama Pengguna
                            @if ($errors->has('employee_name'))
                                <span class="text-warning" role="alert">{{ $errors->first('employee_name') }}</span>
                            @endif
                        </label>
                        <input name="employee_name" type="text" class="form-control" autocomplete="off">
                    </div>
                    <div class="form-group">
                        <label for="">
                            Alamat Email
                            @if ($errors->has('email'))
                                <span class="text-warning" role="alert">{{ $errors->first('email') }}</span>
                            @endif
                        </label>
                        <input name="email" type="text" class="form-control" autocomplete="off">
                    </div>
                    <div class="form-group">
                        <label for="">
                            Password
                            @if ($errors->has('password'))
                                <span class="text-warning" role="alert">{{ $errors->first('password') }}</span>
                            @endif
                        </label>
                        <input name="password" type="password" class="form-control">
                    </div>
                    <div class="form-group">
                        <button class="btn btn-block btn-success btn-flat" type="submit"><i class="fa fa-check"></i> Simpan</button>
                    </div>
                </form>
            </div>
        </div>
    </section>
@endsection

resources/views/employees/edit.blade.php
@extends('layouts.template')

@section('content')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <ol class="breadcrumb">
            <li><a href="{{ url('dashboard') }}"><i class="fa fa-user"></i> Home</a></li>
            <li>Akun</li>
            <li>User</li>
            <li class="active">Edit</li>
        </ol>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <form action="{{ route('employees.update', $employee->id) }}" method="POST">
                    <input type="hidden" name="_method" value="PUT">
                    @csrf

                    <div class="form-group">
                        <label for="">
                            Nama Pengguna
                            @if ($errors->has('employee_name'))
                                <span class="text-warning" role="alert">{{ $errors->first('employee_name') }}</span>
                            @endif
                        </label>
                        <input name="employee_name" type="text" class="form-control" autocomplete="off" value="{{ empty(old('employee_name')) ? $employee->name : old('employee_name') }}">
                    </div>
                    <div class="form-group">
                        <label for="">
                            Alamat Email
                            @if ($errors->has('email'))
                                <span class="text-warning" role="alert">{{ $errors->first('email') }}</span>
                            @endif
                        </label>
                        <input name="email" type="text" class="form-control" autocomplete="off" value="{{ empty(old('email')) ? $employee->email : old('email') }}">
                    </div>
                    <br>
                    <div class="row">
                        <div class="col-md-6 col-xs-6">
                            <a href="{{ url('employees') }}" class="btn btn-default btn-flat btn-block"><i class="fa fa-arrow-left"></i> Kembali</a>
                        </div>
                        <div class="col-md-6 col-xs-6">
                            <button class="btn btn-block btn-primary btn-flat" type="submit"><i class="fa fa-check"></i> Simpan</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <br>
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <button type="button" class="btn btn-danger btn-block" data-toggle="modal" data-target="#delete"><i class="fa fa-trash"></i> Hapus Data Pegawai</button>
            </div>

            <!-- Modal -->
            <div class="modal fade" id="delete" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <form action="{{ route('employees.destroy', $employee->id) }}" method="POST">
                            @csrf
                            <input type="hidden" name="_method" value="DELETE">

                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                                <h4 class="modal-title" id="myModalLabel">Hapus Pegawai <strong>{{ $employee->name }}</strong>?</h4>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-flat btn-default" data-dismiss="modal">Batal</button>
                                <button type="submit" class="btn btn-flat btn-danger">Hapus</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <br><br>
        <hr>
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <form action="{{ route('employees.reset', $employee->id) }}" method="POST">
                    @csrf
                    <input type="hidden" name="_method" value="PUT">
                    <div class="form-group">
                        <label for="">
                            Reset Password
                            @if ($errors->has('password'))
                                <span class="text-warning" role="alert">{{ $errors->first('password') }}</span>
                            @endif
                        </label>
                        <input type="password" class="form-control" name="password" placeholder="Masukkan password baru">
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <button class="btn btn-fill btn-warning btn-block" type="submit"><i class="fa fa-check"></i> Reset Password</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </section>
@endsection

resources/views/employees/index.blade.php
@extends('layouts.template')

@section('content')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <a href="{{ route('employees.create') }}" class="btn btn-primary btn-flat"><i class="fa fa-plus"></i> Tambah User</a>

        <ol class="breadcrumb">
            <li><a href="{{ url('dashboard') }}"><i class="fa fa-user"></i> Home</a></li>
            <li>Akun</li>
            <li class="active">Pegawai</li>
        </ol>
    </section>

    <section class="content">
        <div class="row">
            @foreach ($employees as $employee)
                <a href="{{ route('employees.edit', $employee->id) }}">
                    <div class="col-lg-3 col-xs-12">
                        <div class="info-box">
                            <span class="info-box-icon bg-aqua">
                                <i class="fa fa-user"></i>
                            </span>
                            <div class="info-box-content">
                                <span class="info-box-text">
                                    {{ $employee->name }}
                                </span>
                                <span class="info-box-number">
                                    {{ $employee->email }}
                                </span>
                            </div>
                        </div>
                    </div>
                </a>
            @endforeach
        </div>
    </section>
@endsection