routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('dashboard');
});

Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');

Auth::routes();

// Dashboard
Route::get('/dashboard', 'HomeController@index')->name('dashboard');
// Store & Items Management
Route::resource('stores', 'StoreController');
Route::resource('items', 'ItemController');
Route::put('items/{id}/transfer', 'ItemController@transfer')->name('items.transfer');
Route::put('items/{id}/reduce', 'ItemController@reduce')->name('items.reduce');
// User Management
Route::resource('users', 'UserController');
// Unit Management
Route::resource('units', 'UnitController');
// Employee Management
Route::resource('employees', 'EmployeeController');
Route::put('employees/{id}/reset', 'EmployeeController@reset')->name('employees.reset');

Route::get('setting', 'SettingController@index')->name('setting');

app/Store.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Store extends Model
{
    //
}

app/Http/Controllers/StoreController.php
<?php

namespace App\Http\Controllers;

use App\Item;
use App\Store;
use Illuminate\Http\Request;

class StoreController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    
    public function index()
    {
        $title = 'Daftar Toko';
        $href = '#';
        $icon = '';

        $stores = Store::all();

        return view('stores.index', compact('stores', 'title', 'href', 'icon'));
    }

    public function create()
    {
        $title = 'Tambah Data Toko';
        $href = route('stores.index');
        $icon = 'fa fa-arrow-left';

        return view('stores.create', compact('title', 'href', 'icon'));
    }

    public function store(Request $request)
    {
        $name = $request->input('store_name');
        $city = $request->input('city');
        $district = $request->input('district');
        $address = $request->input('address');

        $request->validate([
            'store_name' => 'required',
            'city' => 'required',
            'district' => 'required',
            'address' => 'required'
        ],[
            'store_name.required' => 'jangan dikosongi!',
            'city.required' => 'jangan dikosongi!',
            'district.required' => 'jangan dikosongi!',
            'address.required' => 'jangan dikosongi juga!'
        ]);

        $store = new Store();
        $store->name = $name;
        $store->city = $city;
        $store->district = $district;
        $store->address = $address;
        $store->save();

        return redirect('stores')->with('message', 'Data toko berhasil ditambahkan.');
    }

    public function edit($id)
    {
        $title = 'Edit Toko';
        $href = route('stores.index');
        $icon = 'fa fa-arrow-left';

        $store = Store::find($id);

        return view('stores.edit', compact('store', 'title', 'href', 'icon'));
    }

    public function update(Request $request, $id)
    {
        $name = $request->input('store_name');
        $city = $request->input('city');
        $district = $request->input('district');
        $address = $request->input('address');

        $request->validate([
            'store_name' => 'required',
            'city' => 'required',
            'district' => 'required',
            'address' => 'required'
        ],[
            'store_name.required' => 'jangan dikosongi!',
            'city.required' => 'jangan dikosongi!',
            'district.required' => 'jangan dikosongi!',
            'address.required' => 'jangan dikosongi juga!'
        ]);

        $store = Store::find($id);
        $store->name = $name;
        $store->city = $city;
        $store->district = $district;
        $store->address = $address;
        $store->save();

        $notify = true;

        return redirect('stores')->with(['message' => 'Data toko berhasil diupdate.']);

    }

    public function show($id)
    {
        $href = route('stores.index');
        $icon = 'fa fa-arrow-left';
        
        $store = Store::find($id);
        $items = Item::where('store_id', $id)->get();
        $title = $store->name;

        return view('stores.show', compact('store', 'items', 'title', 'href', 'icon'));
    }
}

resources/views/stores/create.blade.php
@extends('layouts.template')

@section('content')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <ol class="breadcrumb">
            <li><a href="{{ url('dashboard') }}"><i class="fa fa-user"></i> Home</a></li>
            <li>Toko</li>
            <li class="active">Tambah Baru</li>
        </ol>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <form action="{{ route('stores.store') }}" method="POST">
                    @csrf

                    <div class="form-group">
                        <label for="">
                            Nama Toko
                            @if ($errors->has('store_name'))
                                <span class="text-warning" role="alert">{{ $errors->first('store_name') }}</span>
                            @endif
                        </label>

                        <input type="text" name="store_name" class="form-control" value="{{ old('store_name') }}" autocomplete="off">
                    </div>

                    <div class="form-group">
                        <label for="">
                            Kota/Kabupaten
                            @if ($errors->has('city'))
                                <span class="text-warning" role="alert">{{ $errors->first('city') }}</span>
                            @endif
                        </label>

                        <input type="text" name="city" class="form-control" value="{{ old('city') }}" autocomplete="off">
                    </div>

                    <div class="form-group">
                        <label for="">
                            Kecamatan
                            @if ($errors->has('district'))
                                <span class="text-warning" role="alert">{{ $errors->first('district') }}</span>
                            @endif
                        </label>

                        <input type="text" name="district" class="form-control" value="{{ old('district') }}" autocomplete="off">
                    </div>

                    <div class="form-group">
                        <label for="">
                            Alamat Lengkap
                            @if ($errors->has('address'))
                                <span class="text-warning" role="alert">{{ $errors->first('address') }}</span>
                            @endif
                        </label>

                        <textarea name="address" id="" cols="30" rows="3" class="form-control">{{ old('address') }}</textarea>
                    </div>

                    <button class="btn btn-success btn-flat btn-block" type="submit"><i class="fa fa-save"></i> Simpan</button>

                </form>
            </div>
        </div>
    </section>
@endsection

resources/views/stores/edit.blade.php
@extends('layouts.template')

@section('content')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <ol class="breadcrumb">
            <li><a href="{{ url('dashboard') }}"><i class="fa fa-user"></i> Home</a></li>
            <li>Toko</li>
            <li class="active">Edit</li>
        </ol>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <form action="{{ route('stores.update', $store->id) }}" method="POST">
                    <input type="hidden" name="_method" value="PUT">
                    @csrf

                    <div class="form-group">
                        <label for="">
                            Nama Toko
                            @if ($errors->has('store_name'))
                                <span class="text-warning" role="alert">{{ $errors->first('store_name') }}</span>
                            @endif
                        </label>
                        <input type="text" name="store_name" class="form-control" autocomplete="off" value="{{ empty(old('store_name')) ? $store->name : old('store_name') }}">
                    </div>

                    <div class="form-group">
                        <label for="">
                            Kota/Kabupaten
                            @if ($errors->has('city'))
                                <span class="text-warning" role="alert">{{ $errors->first('city') }}</span>
                            @endif
                        </label>

                        <input type="text" name="city" class="form-control" autocomplete="off" value="{{ empty(old('city')) ? $store->city : old('city') }}">
                    </div>

                    <div class="form-group">
                        <label for="">
                            Kecamatan
                            @if ($errors->has('district'))
                                <span class="text-warning" role="alert">{{ $errors->first('district') }}</span>
                            @endif
                        </label>

                        <input type="text" name="district" class="form-control" autocomplete="off" value="{{ empty(old('district')) ? $store->district : old('district') }}">
                    </div>

                    <div class="form-group">
                        <label for="">
                            Alamat Lengkap
                            @if ($errors->has('address'))
                                <span class="text-warning" role="alert">{{ $errors->first('address') }}</span>
                            @endif
                        </label>

                        <textarea name="address" id="" cols="30" rows="3" class="form-control">{{ empty(old('address')) ? $store->address : old('address') }}</textarea>
                    </div>

                    <button class="btn btn-primary btn-fill btn-block" type="submit"><i class="fa fa-save"></i> Simpan</button>

                </form>
            </div>
        </div>
    </section>
@endsection

resources/views/stores/index.blade.php
@extends('layouts.template')

@section('content')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="row">
            <div class="col-lg-2">
                <a href="{{ route('stores.create') }}" class="btn btn-success btn-flat btn-block"><i class="fa fa-plus"></i> Tambah Toko</a>
            </div>
        </div>
        {{-- <h1>
            Daftar Toko
            <div class="pull-right">
            </div>
        </h1> --}}
    </section>

    <section class="content">
        <div class="row">
            @foreach ($stores as $store)
                <a href="{{ route('stores.show', $store->id) }}">
                    <div class="col-lg-2 col-xs-12">
                        <div class="info-box">
                            <span class="info-box-icon bg-aqua">
                                <i class="fa fa-home"></i>
                            </span>
                            <div class="info-box-content">
                                <span class="info-box-number">
                                    {{ $store->name }}
                                </span>
                                <span class="info-box-text">
                                    {{ $store->address }}
                                </span>
                            </div>
                        </div>
                    </div>
                </a>
            @endforeach
        </div>
    </section>
@endsection

resources/views/stores/show.blade.php
@extends('layouts.template')

@section('content')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            <a href="{{ url('stores') }}"><i class="fa fa-arrow-left"></i></a>
            Item
            <small>{{ $store->name }}</small>

            <div class="pull-right">
                <a href="#" class="btn btn-success btn-flat"><i class="fa fa-plus"></i> Tambah Item</a>
            </div>
        </h1>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-md-6">
                <div class="box">
                    <div class="box-body">
                        <ul class="products-list product-list-in-box">
                            @foreach ($items as $item)
                                <li class="item">
                                    <div class="product-img">
                                        <img src="{{ asset('storage/'.$item->unit->image) }}" alt="Product Image">
                                    </div>
                                    <div class="product-info">
                                        <a href="{{ route('items.edit', $item->id) }}" class="product-title">{{ $item->name }}
                                            <span class="label label-warning pull-right">Rp{{ number_format($item->unit->price * $item->weight) }}</span>
                                            <span class="product-description">Stock: {{ $item->stock }}
                                                <span class="label label-info pull-right">{{ ($item->weight) }} gram</span>                                                
                                            </span>
                                        </a>
                                    </div>
                                </li>
                            @endforeach
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection